# Generated by Django 3.2.18 on 2024-02-29 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_accomadation_hall_hall2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteers_as_event', to='myapp.event')),
                ('event_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteers_event_name', to='myapp.event')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteers_as_student', to='myapp.student')),
            ],
        ),
    ]
