# Generated by Django 3.2.18 on 2024-02-29 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20240229_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='counter',
            field=models.IntegerField(default=5),
        ),
    ]
