# Generated by Django 3.2.18 on 2024-02-29 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_event_counter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='counter',
        ),
    ]
