# Generated by Django 3.2.18 on 2024-02-29 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_remove_event_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='accomadation',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
