# Generated by Django 3.2.18 on 2024-03-02 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_accomadation_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='event_organiser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organiser_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('organiser_name', models.CharField(blank=True, max_length=100, null=True)),
                ('event_name', models.CharField(blank=True, max_length=100, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.event')),
                ('organiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.organiser')),
            ],
        ),
    ]
