# Generated by Django 3.2.18 on 2024-03-02 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_rename_event_organiser_event_has_organiser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event_has_organiser',
            old_name='organiser_email',
            new_name='org_email',
        ),
        migrations.RenameField(
            model_name='event_has_organiser',
            old_name='organiser_name',
            new_name='org_name',
        ),
    ]
