# Generated by Django 3.2.18 on 2024-03-02 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_auto_20240302_1122'),
    ]

    operations = [
        migrations.CreateModel(
            name='Winners',
            fields=[
                ('event', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('name_par', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
    ]
